// <auto-generated />
namespace TTH.LTQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class create_table_CHUCVUs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(create_table_CHUCVUs));
        
        string IMigrationMetadata.Id
        {
            get { return "202104290813139_create_table_CHUCVUs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
